### ISSUE TITLE
Rename jsnext:main version file to have .js extension

### ISSUE THREAD

**Issue by vladshcherbin** [nilennoct/rollup-plugin-dot#1]
It would be great if `jsnext:main` version file had `.js` extension instead of `.mjs` because it gives eslint error:

![screen shot 2018-01-20 at 01 16 47](https://user-images.githubusercontent.com/6711845/35174240-b2336972-fd7f-11e7-9b6d-7be8431c8d5b.png)

It's also possible to rename `jsnext:main` to `module` as it has first class support now.

**Comment by nilennoct** [comment]
Sorry for too late reply. I have published a latest version 1.1.0, which fixes what you mentioned.

`README.md` is also updated to match the latest rollup.

Give me a feedback if you meet any problems.

**Comment by vladshcherbin** [comment]
@nilennoct thank you 😉
